import "bootstrap/dist/css/bootstrap.min.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BootstrapClient from "@/components/BootstrapClient"; // 👈 importamos el componente nuevo

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`main-body ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BootstrapClient />{" "}
        {/* 👈 Esto carga bootstrap.bundle.min.js solo en cliente */}
        {children}
      </body>
    </html>
  );
}
